---
- name: setup inventory
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    server_id: NY1TRITUBUSRV03

  tasks:

    - name: Lookup Server
      clc_server_fact:
        server_id: "{{ server_id }}"
        credentials: false
      register: start_server.servers
    
    - name: Add New Servers to an in-memory Group
      add_host:
        name={{ item.name }}
        ansible_ssh_host={{ item.details.ipAddresses[0].internal }}
        ansible_ssh_user=root
        groupname=SERVERS_GRP
      with_items: start_server.servers
    
- name: install software
  hosts: SERVERS_GRP
  tasks:
  - shell: echo {{ name }}
