---
- name: Read Hostvars for Servers 
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Print PowerState returned by Dynamic Inventory / CLC API
      debug: msg="PowerState={{ hostvars[inventory_hostname]['clc_data']['details']['powerState'] }}"
