---
- name: Stops  Servers
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: stop list of  servers
      clc_server:
        server_ids:
         - NY1TRITTEST124
        state: stopped
